name:                advent-of-code
version:             0.1.0.0
github:              "jallibad/advent-of-code-2021"

data-files:
  data/*.txt

ghc-options:
  - -Wall
  - -fno-warn-tabs
  - -Werror
  - -Wmissing-deriving-strategies

default-extensions:
  - TupleSections
  - LambdaCase
  - MultiWayIf
  - TypeOperators
  - OverloadedStrings
  - OverloadedLists
  - ViewPatterns
  - PatternSynonyms
  - ExplicitForAll
  - TypeApplications
  - ScopedTypeVariables
  - RankNTypes
  - LiberalTypeSynonyms
  - NamedFieldPuns
  - RecordWildCards
  - FlexibleInstances
  - FlexibleContexts
  - DeriveFunctor
  - DeriveFoldable
  - DeriveTraversable
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - ConstrainedClassMethods
  - MultiParamTypeClasses
  - FunctionalDependencies
  - DeriveGeneric
  - NamedWildCards
  - PartialTypeSignatures
  - ExistentialQuantification
  - GADTSyntax
  - GADTs
  - TypeFamilies
  - TypeFamilyDependencies
  - AllowAmbiguousTypes
  - KindSignatures
  - ConstraintKinds
  - DataKinds
  - PolyKinds
  - TypeInType
  - EmptyCase
  - StandaloneDeriving
  - DefaultSignatures
  - DeriveAnyClass
  - DerivingStrategies
  - DisambiguateRecordFields
  - DuplicateRecordFields
  - OverloadedLabels
  - BangPatterns
  - ApplicativeDo
  - NegativeLiterals
  - NumDecimals
  - BinaryLiterals
  - QuasiQuotes
  - UnicodeSyntax
  - NoMonomorphismRestriction
  - PostfixOperators
  - PackageImports
  - StandaloneKindSignatures

library:
  source-dirs: src/
  dependencies:
    - base
    - megaparsec
    - vector

executables:
  Question1:
    main: Main.hs
    dependencies:
      - base
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    source-dirs: app/question1/
  Question2:
    main: Main.hs
    dependencies:
      - base
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    source-dirs: app/question2/
  Question3:
    main: Main.hs
    dependencies:
      - advent-of-code
      - base
      - lens
      - megaparsec
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    source-dirs: app/question3/
  Question4:
    main: Main.hs
    dependencies:
      - advent-of-code
      - base
      - lens
      - megaparsec
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    source-dirs: app/question4/
  Question5:
    main: Main.hs
    dependencies:
      - advent-of-code
      - base
      - lens
      - megaparsec
      - typelits-printf
      - vector
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    source-dirs: app/question5/
  Question6:
    main: Main.hs
    dependencies:
      - advent-of-code
      - base
      - lens
      - megaparsec
      - typelits-printf
      - vector
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -freduction-depth=0
    source-dirs: app/question6/
  Question7:
    main: Main.hs
    dependencies:
      - advent-of-code
      - array
      - base
      - lens
      - megaparsec
      - mtl
      - typelits-printf
      - vector
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -freduction-depth=0
    source-dirs: app/question7/
  Question8:
    main: Main.hs
    dependencies:
      - advent-of-code
      - array
      - base
      - lens
      - megaparsec
      - mtl
      - typelits-printf
      - vector
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -freduction-depth=0
    source-dirs: app/question8/
  Question9:
    main: Main.hs
    dependencies:
      - advent-of-code
      - array
      - base
      - containers
      - lens
      - megaparsec
      - mtl
      - typelits-printf
      - vector
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -freduction-depth=0
    source-dirs: app/question9/
  Question10:
    main: Main.hs
    dependencies:
      - advent-of-code
      - array
      - base
      - containers
      - lens
      - megaparsec
      - mtl
      - typelits-printf
      - vector
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -freduction-depth=0
    source-dirs: app/question10/
