name:                advent-of-code
version:             0.1.0.0
github:              "jallibad/advent-of-code-2021"

data-files:
  data/*.txt

ghc-options:
  - -fno-warn-tabs
  - -Wall
  - -Werror
  - -Wmissing-deriving-strategies
  - -Wredundant-constraints

default-extensions:
  - AllowAmbiguousTypes
  - ApplicativeDo
  - BangPatterns
  - BinaryLiterals
  - ConstrainedClassMethods
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingVia
  - DuplicateRecordFields
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - HexFloatLiterals
  - InstanceSigs
  - LambdaCase
  - LiberalTypeSynonyms
  - MonadComprehensions
  - MultiWayIf
  - NamedFieldPuns
  - NamedWildCards
  - NegativeLiterals
  - NoMonomorphismRestriction
  - NumDecimals
  - NumericUnderscores
  - OverloadedLabels
  - OverloadedLists
  - OverloadedStrings
  - PackageImports
  - ParallelListComp
  - PartialTypeSignatures
  - PatternSynonyms
  - PolyKinds
  - PostfixOperators
  - QuantifiedConstraints
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - RecursiveDo
  - RoleAnnotations
  - ScopedTypeVariables
  - StandaloneDeriving
  - StandaloneKindSignatures
  - TupleSections
  - TypeApplications
  - TypeFamilyDependencies
  - TypeOperators
  - UnboxedSums
  - UnicodeSyntax
  - UnliftedNewtypes
  - ViewPatterns

library:
  source-dirs: src/
  dependencies:
    - base
    - megaparsec
    - vector

executables:
  Question1:
    main: Main.hs
    dependencies:
      - base
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    source-dirs: app/question1/
  Question2:
    main: Main.hs
    dependencies:
      - base
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    source-dirs: app/question2/
  Question3:
    main: Main.hs
    dependencies:
      - advent-of-code
      - base
      - lens
      - megaparsec
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    source-dirs: app/question3/
  Question4:
    main: Main.hs
    dependencies:
      - advent-of-code
      - base
      - lens
      - megaparsec
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    source-dirs: app/question4/
  Question5:
    main: Main.hs
    dependencies:
      - advent-of-code
      - base
      - lens
      - megaparsec
      - typelits-printf
      - vector
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    source-dirs: app/question5/
  Question6:
    main: Main.hs
    dependencies:
      - advent-of-code
      - base
      - lens
      - megaparsec
      - typelits-printf
      - vector
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -freduction-depth=0
    source-dirs: app/question6/
  Question7:
    main: Main.hs
    dependencies:
      - advent-of-code
      - array
      - base
      - lens
      - megaparsec
      - mtl
      - typelits-printf
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -freduction-depth=0
    source-dirs: app/question7/
  Question8:
    main: Main.hs
    dependencies:
      - advent-of-code
      - array
      - base
      - lens
      - megaparsec
      - mtl
      - typelits-printf
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -freduction-depth=0
    source-dirs: app/question8/
  Question9:
    main: Main.hs
    dependencies:
      - advent-of-code
      - base
      - containers
      - lens
      - megaparsec
      - typelits-printf
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -freduction-depth=0
    source-dirs: app/question9/
  Question10:
    main: Main.hs
    dependencies:
      - advent-of-code
      - base
      - containers
      - lens
      - megaparsec
      - typelits-printf
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -freduction-depth=0
    source-dirs: app/question10/
  Question11:
    main: Main.hs
    dependencies:
      - advent-of-code
      - base
      - containers
      - lens
      - megaparsec
      - mtl
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    source-dirs: app/question11/
  Question12:
    main: Main.hs
    dependencies:
      - advent-of-code
      - base
      - containers
      - lens
      - megaparsec
      - mtl
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    source-dirs: app/question12/
